### ISSUE TITLE
Difference from SCE-bobokia

### ISSUE THREAD

**Issue by koallen** [tanhauhau/SCSE-Code-Directory#3]
What's the relation between the 2 repos? I did some search and it seems like I cannot find any repo with this web app. If I want to send some pull requests, which one should I send to?

**Comment by tanhauhau** [comment]
Ok. tl/dr; Let me give you some background of how this 2 repos come to exist.
Initially I tried to consolidate all the repos into a list which is what u see in SCE-bobokia,
but later on, while I was playing on meteor, I created a this web app as a practice project.
Right now, both repos are not maintained.
I think if you have repos to share, you can send PR to SCE-bobokia, update the README.md file with your projects :)

**Comment by koallen** [comment]
Ok, cool. Will send a PR later to SCE-bobokia. :+1:
